name: Decompile PCR

on:
  workflow_dispatch:

jobs:
  decompile:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Rename files
      shell: cmd
      run: |
        rename game.partaa.zip game.partaa
        rename game.partab.zip game.partab
        rename game.partac.zip game.partac
    
    - name: Merge split files
      shell: cmd
      run: |
        copy /b game.partaa+game.partab+game.partac game.droid
        dir game.droid
    
    - name: Download UTMT
      run: |
        curl -L -o utmt.zip https://github.com/UnderminersTeam/UndertaleModTool/releases/download/0.8.4.1/UTMT_CLI_v0.8.4.1-Windows.zip
        Expand-Archive utmt.zip -DestinationPath utmt/
    
    - name: Run Decompile
      run: |
        cd utmt
        ./UndertaleModCli.exe load ../game.droid --script ../decompile.csx
    
    - name: Upload hasil
      uses: actions/upload-artifact@v4
      with:
        name: hasil-decompile
        path: utmt/hasil_decompile.zip
        retention-days: 7
