name: Decompile PCR

on:
  workflow_dispatch:

jobs:
  decompile:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Download game.droid
      run: |
        curl -L -o game.droid.zip https://github.com/botnamelast/pcr-mod/releases/download/kontol/game.droid.zip
        Move-Item game.droid.zip game.droid
        dir game.droid

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Clone UTMT source
      run: |
        git clone --recurse-submodules https://github.com/UnderminersTeam/UndertaleModTool.git utmt-src

    - name: Patch UTMT source
      run: |
        $file = "utmt-src/UndertaleModLib/UndertaleChunks.cs"
        $content = Get-Content $file -Raw
        $old = 'lastChunk = reader.ReadChars(4);'
        $new = 'lastChunk = reader.ReadChars(4); Console.WriteLine($"Scanning chunk: {lastChunk} at pos {reader.Position}");'
        $content = $content.Replace($old, $new)
        Set-Content $file $content
        echo "Patched!"

    - name: Build UTMT CLI
      run: |
        cd utmt-src
        dotnet publish UndertaleModCli -c Release -o ../utmt-build

    - name: Run Decompile
      run: |
        cd utmt-build
        ./UndertaleModCli.exe load ../game.droid --scripts ../decompile.csx
        echo "=== Cek utmt-build ==="
        dir
        echo "=== Cek root ==="
        dir ..
      continue-on-error: true

    - name: Upload hasil
      uses: actions/upload-artifact@v4
      with:
        name: hasil-decompile
        path: utmt-build/hasil_decompile.zip
        retention-days: 7
